### PR TITLE
Follow Azure naming convention

### PR DESCRIPTION
**Pull request by Gijsreyn**
This PR follows the Azure naming convention from: https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations

I already loved the work that's being done, and I don't want to nit on anything whatsoever. I thought of following proper naming conventions as best practice.

### CODE REVIEW

**Comment by denelon** [comment]
@yao-msft I think this one is for you 😊

**Comment by yao-msft** [comment]
These are the actual instances deployed inside our Azure environment. We do not want to destroy and recreate them just because of naming. I have applied the naming suggestion here https://github.com/microsoft/winget-cli-restsource/pull/267/commits/8e044878a5f492f48e5057407b0d0d61e3a5d733

**Comment by yao-msft** [comment]
The suggested naming has been applied to rest source module with this pr https://github.com/microsoft/winget-cli-restsource/pull/267
We are not planning to recreate existing Azure resources just for the naming so I'm closing this pr.
Thanks for the suggestions.

**Comment by Gijsreyn** [comment]
I could have looked a bit further, @yao-msft; thanks a lot for the change and time!

**Pull request closed without merging**
